// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq5f3_7Y5VY6BJahcD_6pOdebFx0oEjUk',
    appId: '1:671825976074:web:f7f2a32cf642511e3bf8f3',
    messagingSenderId: '671825976074',
    projectId: 'sorteador-ipv',
    authDomain: 'sorteador-ipv.firebaseapp.com',
    storageBucket: 'sorteador-ipv.firebasestorage.app',
    measurementId: 'G-W9YCFPCQ82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM6SIbiTr0XpJeetWFitYTrqWiKDWldSk',
    appId: '1:671825976074:android:b8223c06166bffe53bf8f3',
    messagingSenderId: '671825976074',
    projectId: 'sorteador-ipv',
    storageBucket: 'sorteador-ipv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtsIUviR_rI4C7HaOg7ZeXBQ8rYuGLDco',
    appId: '1:671825976074:ios:b1e2b971ca103ef73bf8f3',
    messagingSenderId: '671825976074',
    projectId: 'sorteador-ipv',
    storageBucket: 'sorteador-ipv.firebasestorage.app',
    iosBundleId: 'com.example.sorteoIpvApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtsIUviR_rI4C7HaOg7ZeXBQ8rYuGLDco',
    appId: '1:671825976074:ios:b1e2b971ca103ef73bf8f3',
    messagingSenderId: '671825976074',
    projectId: 'sorteador-ipv',
    storageBucket: 'sorteador-ipv.firebasestorage.app',
    iosBundleId: 'com.example.sorteoIpvApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq5f3_7Y5VY6BJahcD_6pOdebFx0oEjUk',
    appId: '1:671825976074:web:be10dc461f2c054f3bf8f3',
    messagingSenderId: '671825976074',
    projectId: 'sorteador-ipv',
    authDomain: 'sorteador-ipv.firebaseapp.com',
    storageBucket: 'sorteador-ipv.firebasestorage.app',
    measurementId: 'G-3LZK8DBH94',
  );
}
